### ISSUE TITLE
error level for phpstan

### ISSUE THREAD

**Issue by dominikager** [GeneaLabs/action-reviewdog-phpstan#1]
Hello,

how can we set the error level for phpstan?

Thanks!

```
    phpstan-linter:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code into the workspace
                uses: actions/checkout@v2
            -   name: Install dependencies for PHPStan
                uses: php-actions/composer@v5
                with:
                    php_version: 7.4
                    version: 2
                    level: 3
                    command: install --no-scripts --ignore-platform-reqs
            -   name: Run php check code with reviewdog
                uses: GeneaLabs/action-reviewdog-phpstan@1.0.0
                with:
                    github_token: '${{ github.token }}'
                    level: 'error'
                    reporter: 'github-pr-review'
                    target_directory: 'src'
```
